### ISSUE TITLE
Gap filling Design

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/ceps#62]
We need a design for an archival node.  This way historical data from the blockchain can be preserved.

**Comment by dwerner** [comment]
We might want to only periodically flush after each trie written, as this could improve throughput. See the `PERF` note in the contract runtime in [LMDB manual flushing PR](https://github.com/casper-network/casper-node/pull/1695)

**Comment by Fraser999** [comment]
Closing this as it seems like gap-filling will be performed automatically by fast-sync.
