### ISSUE TITLE
Improve Block Rewards

### ISSUE THREAD

**Issue by xcthulhu** [casper-network/ceps#65]
The current block reward scheme is closely coupled to the current consensus implementation.

This makes it hard to introduce improvements to consensus without modifying how block rewards are computed.

We need to design a block reward system that is more modular.

**Comment by cspramit** [comment]
@AlexanderLimonov look in, @afck  just in loop

**Comment by afck** [comment]
We discussed this yesterday and decided against decoupling the rewards from consensus completely: rewards should still depend on actual participation, to discourage "lazy" validators who'd send only one message per era and still get the full rewards.

We still want to address the problem that a skipped block currently punishes everyone, even if it was the proposer's fault. 
We could address this by doubling the rewards for every block whose predecessor is more than one round earlier, i.e. whenever _at least_ one block was skipped, the next block's rewards are doubled (but never tripled). That way, a single faulty validator wouldn't be able to decrease everyone's rewards, but a significant overall slowdown would.

Also, the current system doesn't take into account the switch block, or any finality signatures. A better reward scheme should do that.

**Comment by xcthulhu** [comment]
Okay, we need a consensus independent reward scheme.

As per previous leadership discussions the design/CEP is due this quarter, and it is scheduled for two quarters from now.

**Comment by xcthulhu** [comment]
I have been talking this over with @luis-casper .

Since the auction contract is falling over we need to move to a push-based system.

This exact simplified reward scheme is assumed in this paper which describes an efficient push-based scheme:

https://casperlabs-team.slack.com/files/U02DS3G0NBG/F02PJLUFJ2G/scalable-reward-distribution-paper.pdf

**Comment by goral09** [comment]
> I have been talking this over with @luis-casper .
> 
> Since the auction contract is falling over we need to move to a pull-based system.
> 
> This exact simplified reward scheme is assumed in this paper which describes an efficient pull-based scheme:
> 
> [uploads-ssl.webflow.com/5ad71ffeb79acc67c8bcdaba/5ad8d1193a40977462982470_scalable-reward-distribution-paper.pdf](https://uploads-ssl.webflow.com/5ad71ffeb79acc67c8bcdaba/5ad8d1193a40977462982470_scalable-reward-distribution-paper.pdf)

How is this task and auction state implementation related? One can be changed without the other.

**Comment by KillianH** [comment]
> I have been talking this over with @luis-casper .
> 
> Since the auction contract is falling over we need to move to a pull-based system.
> 
> This exact simplified reward scheme is assumed in this paper which describes an efficient pull-based scheme:
> 
> https://uploads-ssl.webflow.com/5ad71ffeb79acc67c8bcdaba/5ad8d1193a40977462982470_scalable-reward-distribution-paper.pdf

Since I'm a validator I'm interested in this topic. Can you share the PDF publicly ? 🙏

**Comment by afck** [comment]
> Can you share the PDF publicly ? :pray:

I think it's
Batog, Boca, Johnson: _Scalable Reward Distribution on the Ethereum Blockchain_:
http://batog.info/papers/scalable-reward-distribution.pdf

But I agree with @goral09 that it doesn't necessarily mean the actual rewards have to change. The algorithm could be applied per validator to get rid of the overhead per delegator.

**Comment by KillianH** [comment]
> > Can you share the PDF publicly ? :pray:
> 
> I think it's
> Batog, Boca, Johnson: _Scalable Reward Distribution on the Ethereum Blockchain_:
> http://batog.info/papers/scalable-reward-distribution.pdf
> 
> But I agree with @goral09 that it doesn't necessarily mean the actual rewards have to change. The algorithm could be applied per validator to get rid of the overhead per delegator.

This implementation implies that the rewards will not be compounded if I read correctly. 

This will help some jurisdiction with special laws like in Germany where it's pretty bad to have compounded rewards.

But the majority of staking users like that the rewards are compounded.

**Comment by afck** [comment]
I don't think it means that. On the contrary, it only works for compounding rewards?

**Comment by luis-casper** [comment]
The rewards would not be compounded. There are other schemes that do
compound the rewards, but not the one on this paper.
