### ISSUE TITLE
Deprecation of cl_value types

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/ceps#76]

**Comment by piotr-dziubecki** [comment]
Simplify CLTypes (Map, List)

**Comment by EdHastingsCasperLabs** [comment]
We will be deprecating CLValue in 2.0 (will still be retro compatible), and remove it in 3.0. Therefore, it is counter productive / unnecessarily disruptive to do an intermediary removal of a few specific variants of CLValue.
